---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: memcached-operator
  name: memcached-operator-bonny
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: memcached-operator-bonny
subjects:
  - kind: ServiceAccount
    name: memcached-operator-bonny
    namespace: default
